Implementation of Auth
PngWnA/server.kuaaa.net pull request #3
Opened 2021-07-25 12:17 UTC by pandracoon

2021-07-25 13:38 UTC, PngWnA requested changes
Please check out reviews

2021-07-25 13:38 UTC, PngWnA commented on src/lib/auth.ts
> +    //왜 string이면 안되는지...?
아마 decode된 친구 type 찍어보면 Object로 나올거임

2021-07-25 13:38 UTC, PngWnA commented on src/lib/error.ts
> +export { CustomError };
파일 끝날때 newline 추가해주세요

2021-07-25 13:38 UTC, PngWnA commented on src/router/auth/auth.ts
> +        const row = await getRepository(User).findOne({where: {id: uid}});
혹시 User.create로도 DB에 입출력이 되는지 확인해볼 수 있니

2021-07-25 13:38 UTC, PngWnA commented on src/router/auth/auth.ts
> +        else throw new CustomError('REGISTER_FAILED', 401, 'Input ID is already in use.');
Check
https://stackoverflow.com/questions/9269040/which-http-response-code-for-this-email-is-already-registered/9270432
and decide which status code is the best for describing this error.

2021-07-25 13:38 UTC, PngWnA commented on src/router/users/spec.ts
> + *      "password": "sha512:h7IpzeEKm/9Tm1UmXwQrdw==:123456:512:iR8v2BQ/G4qWykMFmb1YSpAs5y7f0+C4SZ0g40HP+gZ905xH2SmAr68Gh6rH659Jm8hvzuYqBXmPhzNJwcPUeytSOvDJUlg1t7NN6AIdjKp0CiCjQKsnpXDWBktdlyFyur/yvXQ
Please check whether uploading this token to the public as an example is violating anyone's privacy.
And reply.

2021-07-25 13:38 UTC, PngWnA commented on src/router/users/users.ts
> +//TODO: should check permission to call this method
What is the purpose of this method?

2021-07-25 13:38 UTC, PngWnA commented on src/server.ts
> +app.use((err, req, res, next) => {
Good abstraction!

2021-07-26 10:12 UTC, pandracoon commented on src/router/users/users.ts
> +//TODO: should check permission to call this method
처음에 작업 시작할때 명세에 DB에 있는 모든 User정보를 GET하는 API가 있었어서 구현해둔건데,
누구나 호출할 수 있으면 안될 것 같아서 나중에 User별로 등급/권한을 추가하면 그때 적용하려고 TODO로 표시해뒀어요

2021-07-26 10:51 UTC, pandracoon commented on src/router/auth/auth.ts
> +        const row = await getRepository(User).findOne({where: {id: uid}});
지금 구현된 방식이 Create로 된것 아닌가요?
`const row = await getRepository(User).findOne({where: {id: uid}});

        if(row === undefined){
        const password: string = req.body.password;
        const encryptedPassword = await generatePassword(password);

        const user: User = await getRepository(User).create({
            id: uid,
            password: encryptedPassword,
            name: req.body.name,
            sid: req.body.sid,
            belong: req.body.belong,
            email: req.body.email
        });
        getRepository(User).save(user);`

2021-07-26 11:56 UTC, susemeee commented on src/lib/error.ts
> +export { CustomError };
이런 사소한(?)것들은 prettier + editorconfig으로 때웁시다

2021-07-26 11:57 UTC, susemeee commented on src/router/auth/auth.ts
> +        else throw new CustomError('REGISTER_FAILED', 401, 'Input ID is already in use.');
request 핸들러에서는 에러케이스여도 일단 항상 response는 줘야 함

2021-07-26 11:57 UTC, susemeee commented on src/router/users/spec.ts
> + *      "password": "sha512:h7IpzeEKm/9Tm1UmXwQrdw==:123456:512:iR8v2BQ/G4qWykMFmb1YSpAs5y7f0+C4SZ0g40HP+gZ905xH2SmAr68Gh6rH659Jm8hvzuYqBXmPhzNJwcPUeytSOvDJUlg1t7NN6AIdjKp0CiCjQKsnpXDWBktdlyFyur/yvXQ
테스트 케이스의 fixture니깐 괜찮지않음?

2021-07-26 11:58 UTC, susemeee commented on src/router/users/users.ts
> +//TODO: should check permission to call this method
미들웨어 필요

2021-07-26 13:26 UTC, PngWnA commented on src/lib/error.ts
> +export { CustomError };
@susemeee editorconfig는 뭔가여

2021-07-26 13:27 UTC, PngWnA commented on src/router/auth/auth.ts
> +        const row = await getRepository(User).findOne({where: {id: uid}});
ㅇㅇ 그런데 혹시
`await User.create`도 똑같이 작동하는지 알아보고싶었음
내가 나중에 테스트해봐야겠다

2021-07-26 13:29 UTC, PngWnA commented on src/router/auth/auth.ts
> +        else throw new CustomError('REGISTER_FAILED', 401, 'Input ID is already in use.');
@susemeee 그 response를 주는게 CustomError의 constructor에 구현되어있더라고요
저게 나은지 여기서 처리하는게 나은지는 모르겠지만

2021-07-26 13:30 UTC, PngWnA commented on src/router/users/spec.ts
> + *      "password": "sha512:h7IpzeEKm/9Tm1UmXwQrdw==:123456:512:iR8v2BQ/G4qWykMFmb1YSpAs5y7f0+C4SZ0g40HP+gZ905xH2SmAr68Gh6rH659Jm8hvzuYqBXmPhzNJwcPUeytSOvDJUlg1t7NN6AIdjKp0CiCjQKsnpXDWBktdlyFyur/yvXQ
음 뭐 문제있는 데이터느 안넣었겠죠?

2021-07-26 13:31 UTC, PngWnA commented on src/router/auth/auth.ts
> +        else throw new CustomError('REGISTER_FAILED', 409, 'Input ID is already in use.');
409 아니면 200을 주긴 함
200을 주는 사람들은 id가 중복된게 client error는 아니라는 의견임

2021-07-26 13:32 UTC, PngWnA commented on src/lib/error.ts
> +export { CustomError };
아 톡에서 물어볼게여

2021-07-26 16:17 UTC, pandracoon commented on src/router/users/spec.ts
> + *      "password": "sha512:h7IpzeEKm/9Tm1UmXwQrdw==:123456:512:iR8v2BQ/G4qWykMFmb1YSpAs5y7f0+C4SZ0g40HP+gZ905xH2SmAr68Gh6rH659Jm8hvzuYqBXmPhzNJwcPUeytSOvDJUlg1t7NN6AIdjKp0CiCjQKsnpXDWBktdlyFyur/yvXQ
사실 그냥 아무거나 넣고 만든거긴 해요

2021-07-27 01:46 UTC, PngWnA commented on src/router/users/users.ts
> +//TODO: should check permission to call this method
나중에 미들웨어로 쓸 수 있게 해놓는것도 좋을거임

2021-07-27 01:47 UTC, PngWnA approved these changes

2021-07-27 01:47 UTC, PngWnA commented
나중에 eslint같은 CI 붙이죠

2021-07-27 01:47 UTC, merged