Implementation of Image Handling
PngWnA/server.kuaaa.net pull request #6
Opened 2021-08-10 10:28 UTC by pandracoon

<Image>
1. Image를 다루기 위한 package
- multer
- @types/multer
2. Image 모델
3. Image를 서버에 저장하고 가져오는 API
4. API docs

<Other>
1. 모든 파일 Code format 맞춰서 수정
2. User 모델에 profileImageId 프로퍼티를 추가 => 관련 메소드, docs 수정

2021-08-10 14:17 UTC, PngWnA requested changes
Check out two reviews

2021-08-10 14:17 UTC, PngWnA commented on src/router/images/spec.ts
> + *         "path": "src\\res\\image\\fad6c4b32695ff7e0a35f27fd42ba7b9",
path should be an url available to client-side
ex) server.kuaaa.net/api/image/fad6c4b32695ff7e0a35f27fd42ba7b9

2021-08-11 11:22 UTC, susemeee commented on package.json
> +    "@types/multer": "^1.4.7",
`@types/x` 는 웬만하면 devDependencies(`yarn add --dev x`)로

2021-08-11 11:22 UTC, susemeee commented on src/lib/auth.ts
>      console.log(decoded);
콘솔지워주세요

2021-08-11 11:22 UTC, susemeee commented on src/lib/auth.ts
> +    if (typeof decoded === 'string') throw new Error('type is string');
+1 에러메시지는 받는(API/function callee) 입장에서 작성해야함. `type is string` 와 같은 메시지는 로그로 남기는게 더 적절

2021-08-11 11:22 UTC, susemeee commented on src/router/images/images.ts
> +const upLoadImage: RequestHandler = async (req, res, next) => {
`uploadImage`

2021-08-11 11:22 UTC, susemeee commented on src/router/images/images.ts
> +      for (let i = 0; i < size; ++i)
`i++`

2021-08-11 11:22 UTC, susemeee commented on src/router/images/images.ts
> +    if (req.files !== undefined) {
`req.files && Array.isArray(req.files)` (Array가 아니면 req.files.length가 없을수도 있음)

2021-08-11 12:43 UTC, pandracoon commented on src/lib/auth.ts
> +    if (typeof decoded === 'string') throw new Error('type is string');
오우 저거 Error 연습한다고 대충 적어둔건데 생각해보니 처리를 안해뒀었네요

2021-08-11 13:53 UTC, susemeee commented on src/lib/model/user.ts
> +  profileImageId!: string;
Image OneToOne으로

2021-08-16 13:43 UTC, susemeee reviewed
+ exception handler에 `next(err)` 만 해두고 끝나는데 그 상황에서 response를 적절히 던져주는지 확인 필요

다른 부분들은 굿

2021-08-16 13:43 UTC, susemeee commented on src/lib/auth.ts
>    const iter = parseInt(iterStr, 10);
보통 이런 상황에서는 `Number()` 가 더 나음

2021-08-16 13:43 UTC, susemeee commented on src/router/auth/auth.ts
> +      const { name, sid, belong, email, profileImageId } = req.body;
nullish check 필요할듯

2021-08-16 13:43 UTC, susemeee commented on src/router/auth/auth.ts
> +      getRepository(User).save(user);
여기 진짜 `await` 안 쓰는게 맞아?

2021-08-16 13:43 UTC, susemeee commented on src/router/auth/auth.ts
> +const getProfileImage = async (profileImageId: string | undefined) => {
equal to `(profileImageId?: string)`

2021-08-16 13:43 UTC, susemeee commented on src/router/auth/auth.ts
> +    } else return undefined;
`return Promise.resolve(null);`

2021-08-16 13:43 UTC, susemeee commented on src/router/auth/auth.ts
> +    if (row !== undefined) {
차라리 `if (row)` 가 나을듯

2021-08-16 13:43 UTC, susemeee commented on src/router/auth/auth.ts
> +      throw new CustomError('LOGIN_FAILED', 409, 'Username does not exist.');
`409` 대신 `401`

2021-08-16 13:43 UTC, susemeee commented on src/router/auth/auth.ts
> +    const row = getRepository(ExpiredToken).create({
nullish check

2021-08-16 13:43 UTC, susemeee commented on src/router/images/images.ts
> +  return { id: id, mimetype: mimetype, size: size };
equal to `return { id, mimetype, size }`

2021-08-16 13:46 UTC, susemeee commented on src/router/auth/auth.ts
> +    } else return undefined;
아 아니다 AsyncFunction이라 상관없을듯

2021-08-16 13:47 UTC, PngWnA commented on src/lib/auth.ts
>    const iter = parseInt(iterStr, 10);
저거 복붙한거라 ㅎㅎ

2021-08-16 13:48 UTC, PngWnA commented on src/router/auth/auth.ts
> +      getRepository(User).save(user);
@pandracoon

2021-08-16 13:49 UTC, PngWnA commented on src/router/auth/auth.ts
> +const getProfileImage = async (profileImageId: string | undefined) => {
저거 아마 그냥 저렇게 적어두면 getProfileImage가 undefined일수도 있다고 에러 뱉어서 재건이가 저렇게 해놓은듯

2021-08-16 13:49 UTC, PngWnA commented on src/router/auth/auth.ts
> +      throw new CustomError('LOGIN_FAILED', 409, 'Username does not exist.');
차이를 설명해주셔야할듯 합니다

2021-08-16 13:51 UTC, PngWnA approved these changes
LGTM

2021-08-16 17:12 UTC, pandracoon commented on src/router/auth/auth.ts
> +      getRepository(User).save(user);
아 저건 제가 까먹음... 쓰는게 맞아요 안쓰고 테스트 해보니 당연히 문제생김

2021-08-17 01:06 UTC, susemeee commented on src/router/auth/auth.ts
> +const getProfileImage = async (profileImageId: string | undefined) => {
아 같은 syntax라는 뜻임

2021-08-17 01:07 UTC, susemeee commented on src/router/auth/auth.ts
> +      throw new CustomError('LOGIN_FAILED', 409, 'Username does not exist.');
오우 오늘 회의때 해보겠음

2021-08-17 01:07 UTC, susemeee commented on src/router/auth/auth.ts
> +      getRepository(User).save(user);
딴데도 있으니 확인 바람

2021-08-17 10:16 UTC, pandracoon commented on src/router/auth/auth.ts
> +const getProfileImage = async (profileImageId: string | undefined) => {
자꾸 undefined일수도 있다,가 거슬려서 고민하다 적은건데 생각해보니 ?가 있었네요

2021-08-17 10:19 UTC, pandracoon commented on src/router/auth/auth.ts
> +    const row = getRepository(ExpiredToken).create({
만료된 토큰 담아두는 곳인데, 중복되는 토큰이 있는 경우가 있을까 싶어서 그냥 뒀습니다
null일 가능성이 있으면 무조건 하는게 맞나요?

2021-08-17 10:35 UTC, pandracoon commented on src/server.ts
Error Handler를 하나 만들어뒀는데, next(err)로 넘어오는 Error 객체 종류는 무조건 3가지 중에 하나일 거라고 생각해서 이렇게 처리했습니다.  

1. 응답 코드가 500이 아닌 경우 => CustomError 객체로 throw해두면 여기서 error message를 클라에 보내줌
2. 응답 코드가 500이지만 error의 원인을 아는 경우 => CustomError 객체로 throw 해두면 여기서 error message를 콘솔에 띄워주고 클라에는 Something went wrong만 보냄
3. try에서 캐치한 error의 경우 => Something went wrong만 클라에 보내고 에러 정보를 콘솔로 출력.

2021-08-17 10:35 UTC, pandracoon commented on src/server.ts
@susemeee 위에서 Error Handler 관련해서 적어봤어요

2021-08-17 10:40 UTC, pandracoon commented on src/server.ts
> +  else res.status(500).send({ msg: 'Something went wrong...' });
Error Handler를 하나 만들어뒀는데, next(err)로 넘어오는 Error 객체 종류는 무조건 3가지 중에 하나일 거라고 생각해서 이렇게 처리했습니다.  

1. 응답 코드가 500이 아닌 경우 => CustomError 객체로 throw해두면 여기서 error message를 클라에 보내줌
2. 응답 코드가 500이지만 error의 원인을 아는 경우 => CustomError 객체로 throw 해두면 여기서 error message를 콘솔에 띄워주고 클라에는 Something went wrong만 보냄
3. try에서 캐치한 error의 경우 => Something went wrong만 클라에 보내고 에러 정보를 콘솔로 출력.

2021-08-17 10:42 UTC, pandracoon commented on src/server.ts
> +  else res.status(500).send({ msg: 'Something went wrong...' });
@susemeee 위에서 Error Handler 관련해서 적어봤어요

아 근데 저거 리뷰할때 코드 4줄밖에 못고르나요ㅋㅋㅋ 블럭하고 +눌러도 영 안되네

2022-09-27 15:11 UTC, closed without merging